// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIQli4QQaBm5IRkg2v08YE-aD-mUoVLwE',
    appId: '1:676102038427:web:f750b13538fe16ef01f73e',
    messagingSenderId: '676102038427',
    projectId: 'emergency-map-sy',
    authDomain: 'emergency-map-sy.firebaseapp.com',
    storageBucket: 'emergency-map-sy.firebasestorage.app',
    measurementId: 'G-8LD1JGZE9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdip6REiBIACj-ukm5TLx_ayP5Usu3D3Q',
    appId: '1:676102038427:android:404177cb871a6f3501f73e',
    messagingSenderId: '676102038427',
    projectId: 'emergency-map-sy',
    storageBucket: 'emergency-map-sy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVUNpf34az4dC29Ujt5IDq_qcEIHBPX5Q',
    appId: '1:676102038427:ios:d96632538ef9a98201f73e',
    messagingSenderId: '676102038427',
    projectId: 'emergency-map-sy',
    storageBucket: 'emergency-map-sy.firebasestorage.app',
    iosBundleId: 'com.example.emergencyMapSy',
  );
}
